Create a program to read a JSON file, convert it into a DataFrame, and export it to a CSV

Import libraries

In [10]:
import numpy as np
import pandas as pd

Create DataFrame from JSON

In [11]:
json_file="data.json"
df = pd.read_json(json_file)
df

   index     name  age  salary
0      0    alice   25   50000
1      1      bob   30   60000
2      2  charlie   35   70000

Export to CSV

In [12]:
json_file="data.json"
df = pd.read_json(json_file)
df

   index     name  age  salary
0      0    alice   25   50000
1      1      bob   30   60000
2      2  charlie   35   70000

In [13]:
csv_file=df.to_csv('data.csv')
csv_file

Print confirmation

In [14]:
print('csv file is created successfully')

csv file is created successfully