
Load a dataset and perform indexing, sorting, and basic filtering operations.

Import libraries

In [10]:
import pandas as pd
import numpy as np

Create dataset

In [11]:
arr={"index":[0,1,2],
     "name":["alice","bob","charlie"],
     "age":[25,30,35],
     "salary":[50000,60000,70000]}

Convert to DataFrame

In [12]:
df = pd.DataFrame(arr)
df

   index     name  age  salary
0      0    alice   25   50000
1      1      bob   30   60000
2      2  charlie   35   70000

Indexing

In [13]:
index =df.set_index("age")
index

     index     name  salary
age
25       0    alice   50000
30       1      bob   60000
35       2  charlie   70000

Sorting

In [14]:
sort=df.sort_values("name")
sort

   index     name  age  salary
0      0    alice   25   50000
1      1      bob   30   60000
2      2  charlie   35   70000

Filtering

In [15]:
filter=df[df["salary"] >= 60000]
filter

   index     name  age  salary
1      1      bob   30   60000
2      2  charlie   35   70000